# server settings
server:
  port: 8000

# security
security:

# database settings
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site_scrapper
    username: root
    password: cjsrn1992!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret-key: HYUNGYU.LEE_SECRET!!
