# server settings
server:
  port: 8000

# database settings
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site_scrapper
    username: root
    password: cjsrn1992!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jwt:
    expire-day: 1
    secret-key: HYUNGYU.LEE_SECRET!!
